# Nome do Workflow
name: Deploy Next.js to GitHub Pages

on:
  # Roda quando um push é feito na branch `main`
  push:
    branches: ["main"]

  # Permite que você rode este workflow manualmente na aba Actions
  workflow_dispatch:

# Define as permissões para o token do GitHub poder fazer o deploy
permissions:
  contents: read
  pages: write
  id-token: write

# Permite apenas um deploy por vez
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Job de construção (Build)
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (Baixar o código)
        uses: actions/checkout@v4
      
      # Este passo detecta se você usa 'npm' ou 'yarn'
      - name: Detect package manager
        id: detect-package-manager
        run: |
          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
            echo "manager=yarn" >> $GITHUB_OUTPUT
            echo "command=install" >> $GITHUB_OUTPUT
            echo "runner=yarn" >> $GITHUB_OUTPUT
            exit 0
          elif [ -f "${{ github.workspace }}/package.json" ]; then
            echo "manager=npm" >> $GITHUB_OUTPUT
            echo "command=ci" >> $GITHUB_OUTPUT
            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "Não foi possível determinar o gerenciador de pacotes"
            exit 1
          fi

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Usa a versão 20 do Node.js
          cache: ${{ steps.detect-package-manager.outputs.manager }}

      - name: Configurar GitHub Pages para Next.js
        uses: actions/configure-pages@v5
        with:
          static_site_generator: next

      - name: Restaurar cache para acelerar builds futuros
        uses: actions/cache@v4
        with:
          path: |
            .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**/*.[jt]s', '**/*.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lint.json', '**/yarn.lock') }}-

      - name: Instalar dependências
        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}

      - name: Construir o site com Next.js
        run: ${{ steps.detect-package-manager.outputs.runner }} next build

      - name: Fazer upload do artefato (pasta 'out')
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  # Job de implantação (Deploy)
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build # Este job só roda depois que o 'build' terminar
    steps:
      - name: Fazer deploy no GitHub Pages
        id: deployment
